config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from users.views import (
    LoginView,
    log_out,
    SignUpView,
    UserProfileView,
    UpdateProfileView,
    UpdatePasswordView,
    complete_verification,
    github_login,
    github_callback,
    kakao_login,
    kakao_callback,
)

app_name = "users"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("login/github", github_login, name="github-login"),
    path("login/github/callback", github_callback, name="github-callback"),
    path("login/kakao", kakao_login, name="kakao-login"),
    path("login/kakao/callback", kakao_callback, name="kakao-callback"),
    path("logout", log_out, name="logout"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", complete_verification, name="complete_verfication"),
    path("update", UpdateProfileView.as_view(), name="update"),
    path("update-password", UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>", UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<footer
    class="w-full mx-auto text-center px-0 py-4 border-t font-medium text-gray-600 flex flex-col justify-between text-xs md:px-40 md:flex-row md:py-10 md:text-base">
    <div class="my-auto">
        &copy; 2020
        <a href="https://github.com/alstn2468" target="_blank"
            class="text-gray-700 font-bold transition-all duration-300 hover:text-blue-700">
            Minsu Kim</a>. All rights reserved.
    </div>
    <div class="pt-3 lg:pt-0 md:pt-0">
        <a href="https://github.com/alstn2468" target="_blank"
            class="text-gray-500 hover:text-gray-700 transition-colors duration-300">
            <i class="fab fa-github-square text-xl md:text-3xl"></i>
        </a>
        <a href="https://www.facebook.com/profile.php?id=100003769223078" target="_blank"
            class="text-gray-500 hover:text-gray-700 transition-colors duration-300">
            <i class="fab fa-facebook-square text-xl md:text-3xl"></i>
        </a>
        <a href="https://www.instagram.com/minsu._.0102/" target="_blank"
            class="text-gray-500 hover:text-gray-700 transition-colors duration-300">
            <i class="fab fa-instagram-square text-xl md:text-3xl"></i>
        </a>
        <a href="https://www.linkedin.com/in/minsu-kim-336289160/" target="_blank"
            class="text-gray-500 hover:text-gray-700 transition-colors duration-300">
            <i class="fab fa-linkedin text-xl md:text-3xl"></i>
        </a>
        <a href="https://alstn2468.github.io/" target="_blank"
            class="text-gray-500 hover:text-gray-700 transition-colors duration-300">
            <i class="fas fa-rss-square text-xl md:text-3xl"></i>
        </a>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
  {% for message in messages %}
  <li
    class="message font-medium bg-gray-700 rounded-full z-10 text-white py-4 px-6 w-64 text-center
    {% if message.tags %}{{ message.tags }}{% endif %}"
  >
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-xs font-medium h-full mr-1 md:text-base md:mr-6 ">
    {% if user.is_authenticated %}
    <li class="nav-link w-12 text-center md:w-22 md:ml-6">
        <a href="{{ user.get_absolute_url }}" class="w-full text-center md:py-10">Profile</a>
    </li>
    <li class="nav-link w-12 text-center md:w-22 md:ml-6">
        <a href="{% url "users:logout" %}" class="w-full text-center md:py-10">Logout</a>
    </li>
    {% else %}
    <li class="nav-link w-12 text-center md:w-20 md:ml-6">
        <a href="{% url "users:login" %}" class="w-full text-center md:py-10">Login</a>
    </li>
    <li class="nav-link w-12 text-center md:w-20 md:ml-6">
        <a href="{% url "users:signup" %}" class="w-full text-center md:py-10">Sign Up</a>
    </li>
    {% endif %}
</ul>

templates/partials/social_login.html
{% load static %}
<div class="btn-wrapper">
    <a href="{% url 'users:github-login' %}" class="btn bg-gray-800 text-white">
        <i class="fab fa-github fa-lg mr-1"></i>
        Continue With Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn border-kakao bg-kakao text-black">
        <i class="fas fa-comment fa-lg mr-1"></i>
        Continue With Kakao
    </a>
</div>

<div class="flex items-center w-11/12 mt-2 mb-4 md:mt-3 md:mb-6 md:w-10/12">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>