config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from rooms.views import RoomDetailView, SearchView, RoomEditView

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", RoomEditView.as_view(), name="edit"),
    path("search/", SearchView.as_view(), name="search"),
]

templates/mixins/room_card.html
<div class="w-1/2 mb-3 px-2 overflow-hidden md:w-1/4 md:mb-10">
    <a href={% url 'rooms:detail' room.pk %}>
        <div class="w-full h-32 bg-cover bg-center rounded-lg mb-2 md:h-64"
            style="background-image: url({{ room.first_photo }});">
        </div>
        <div class="flex justify-between mb-1 truncate md:mb-2">
            <div class="w-4/5 overflow-hidden flex items-center">
                {% if room.host.is_superhost %}
                <span
                    class="uppercase border-black border rounded py-0 px-1 font-semibold text-xs text-black mr-1 md:py-px md:mr-2">superhost</span>
                {% endif %}
                <span class="text-xs text-gray-600 block truncate md:text-sm">{{ room.city }} ·
                    {{ room.country.name }}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{ room.total_rating }}
            </span>
        </div>
        <span class="text-black w-11/12 block truncate text-xs md:text-base">{{ room.name }}</span>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avater %}
<div
  class="{{ h_and_w|default:'h-20 w-20' }} rounded-full bg-cover"
  style="background-img: url({{ user.avater.url }});"
>
{% else %}
<div
  class="{{ h_and_w|default:'h-20 w-20' }}
    bg-gray-700 rounded-full text-white flex
    justify-center items-center overflow-hidden"
>
  <span class="{{ text|default:'text-3xl' }}">
    {{ user.first_name|first }}
  </span>
{% endif %}
</div>