config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from rooms.views import RoomDetailView, SearchView, RoomEditView

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", RoomEditView.as_view(), name="edit"),
    path("search/", SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core.models import AbstractTimeStamp


class AbstractItem(AbstractTimeStamp):
    """Abstract Item Model

    Inherit:
        AbstractTimeStamp

    Fields:
        name       : CharField
        created_at : DateTimeField
        updated_at : DateTimeField

    Method:
        __str__ : return name
    """

    name = models.CharField(max_length=80, unique=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """RoomType Model

    Inherit:
        AbstractItem
    """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):
    """Amenity Model

    Inherit:
        AbstractItem
    """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """Facility Model

    Inherit:
        AbstractItem
    """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """HouseRule Model

    Inherit:
        AbstractItem
    """

    class Meta:
        verbose_name = "House Rule"


class Photo(AbstractTimeStamp):
    """Photo Model

    Inherit:
        AbstractTimeStamp

    Fields:
        caption    : CharField
        file       : ImageField
        room       : Room Model (1:N)
        created_at : DateTimeField
        updated_at : DateTimeField

    Method:
        __str__ : return caption
    """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(AbstractTimeStamp):
    """Room Model

    Inherit:
        AbstractTimeStamp

    Fields:
        name         : CharField
        description  : TextField
        country      : CountryField
        city         : CharField
        price        : IntegerField
        address      : CharField
        guests       : IntegerField
        beds         : IntegerField
        bedrooms     : IntegerField
        baths        : IntegerField
        check_in     : TimeField
        check_out    : TimeField
        instant_book : BooleanField
        host         : users app User model (1:N)
        room_type    : RoomType model (1:N)
        amenities    : Amenity model (N:N)
        facilities   : Facility model (N:N)
        house_rules  : HouseRule model(N:N)
        created_at   : DateTimeField
        updated_at   : DateTimeField

    Method:
        __str__      : return name
        save         : change capitalized city name and save
        total_rating : return all reviews rating avg
        first_photo  : return room's first photo file url
    """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()

        if len(all_reviews) == 0:
            return 0

        all_ratings = 0

        for review in all_reviews:
            all_ratings += review.rating_average()

        return round(all_ratings / len(all_reviews), 2)

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except Exception:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

rooms/forms.py
from django import forms
from rooms.models import RoomType, Amenity, Facility
from django_countries.fields import CountryField


class SearchForm(forms.Form):
    """Room application search form

    Inherit:
        forms.Form

    Field:
        city         : CharField
        country      : CountryField.formfield
        room_type    : ModelChoiceField (RoomType)
        price        : IntegerField
        guests       : IntegerField
        bedrooms     : IntegerField
        beds         : IntegerField
        baths        : IntegerField
        instant_book : BooleanField
        is_superhost : BooleanField
        amenities    : ModelMultipleChoiceField (Amenity)
        facilities   : ModelMultipleChoiceField (Facility)
    """

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    is_superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
from django.views.generic import ListView, DetailView, UpdateView, View
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404
from rooms.models import Room
from rooms.forms import SearchForm


class HomeView(ListView):
    """rooms application HomeView class
    Display list of room query set

    Inherit             : ListView
    Model               : Room
    paginate_by         : 10
    paginate_orphans    : 5
    ordering            : created_at
    context_object_name : rooms
    Templates name      : rooms/rooms_list.html
    """

    model = Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created_at"
    context_object_name = "rooms"

    def dispatch(self, request, *args, **kwargs):
        try:
            return super(HomeView, self).dispatch(request, *args, **kwargs)

        except Http404:
            return redirect(reverse("core:home"))


class RoomDetailView(DetailView):
    """rooms application RoomDetailView Class
    Display detail of room object

    Inherit             : DetailView
    Model               : Room
    Templates name      : rooms/room_detail.html
    """

    model = Room


class SearchView(View):
    """rooms application SearchView Class
    Display list of rooms searched by city

    Inherit             : View
    Templates name      : rooms/search.html
    """

    def get(self, request):
        country = request.GET.get("country")

        if country:
            form = SearchForm(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                is_superhost = form.cleaned_data.get("is_superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if is_superhost is True:
                    filter_args["host__is_superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                rooms = Room.objects.filter(**filter_args)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class RoomEditView(UpdateView):
    """rooms application RoomEditView Class
    Update room object fields data

    Inherit             : UpdateView
    Templates name      : rooms/room_edit.html
    """

    model = Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}ROOM DETAIL{% endblock page_name %}

{% block content %}
    <div>
        <h1>{{ room.name }}</h1>
        <h3>{{ room.description }}</h3>
    </div>

    <div>
        <h2>By : {{ room.host.username }}
        {% if room.host.is_superhost %}
            (superhost)
        {% endif %}
        </h2>

        <h3>Amenities</h3>
        <ul>
        {% for amenity in room.amenities.all %}
            <li>{{ amenity }}</li>
        {% endfor %}
        </ul>

        <h3>Facilities</h3>
        <ul>
        {% for facility in room.facilities.all %}
            <li>{{ facility }}</li>
        {% endfor %}
        </ul>

        <h3>House Rules</h3>
        <ul>
        {% for house_rule in room.house_rules.all %}
            <li>{{ house_rule }}</li>
        {% endfor %}
        </ul>
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_name %}{{ room.name }}{% endblock page_name %}

{% block content %}
<div class="-mt-5 container max-w-full h-75vh flex mb-20">
    <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{ room.first_photo }})"></div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_four_photos %}
        <div style="background-image:url({{ photo.file.url }})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
        {% endfor %}
    </div>
</div>
<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between">
            <div class="mb-5">
                <h4 class="text-3xl font-medium mb-px">{{ room.name }}</h4>
                <span class="text-gray-700 font-light">{{ room.city }}</span>
            </div>
            <a href="{{ room.host.get_absolute_url }}" class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=room.host %}
                <span class="mt-2 text-gray-500">{{ room.host.first_name }}</span>
            </a>
        </div>
        <div class="flex border-section">
            <span class="mr-5 font-light">{{ room.room_type }}</span>
            <span class="mr-5 font-light">{{ room.beds }} bed{{ room.beds|pluralize }}</span>
            <span class="mr-5 font-light">{{ room.bedrooms }} bedroom{{ room.bedrooms|pluralize }}</span>
            <span class="mr-5 font-light">{{ room.baths }} bath{{ room.baths|pluralize }}</span>
            <span class="mr-5 font-light">{{ room.guests }} guest{{ room.guests|pluralize }}</span>
        </div>
        <p class="border-section">
            {{ room.description }}
        </p>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">Amenities</h4>
            {% for amenity in room.amenities.all %}
                <li class="mb-2">{{ amenity }}</li>
            {% endfor %}
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">Facilities</h4>
            {% for facility in room.facilities.all %}
                <li class="mb-2">{{ facility }}</li>
            {% endfor %}
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">House Rules</h4>
            {% for house_rule in room.house_rules.all %}
                <li class="mb-2">{{ house_rule }}</li>
            {% endfor %}
        </div>
        <div class="mt-10">
            <h4 class="font-medium text-2xl mb-5">Reviews</h4>
            <div class="flex items-center">
                <div>
                    <i class="fas fa-star text-teal-500"></i>
                    <span class="font-bold text-xl">{{ room.total_rating }}</span>
                </div>
                <div class="h-4 w-px bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{ room.reviews.count }}</span>
                    <span>review{{ room.reviews.count|pluralize }}</span>
                </div>
            </div>
            <div class="mt-10">
                {% for review in room.reviews.all  %}
                    <div class="border-section">
                        <div class="mb-3 flex">
                            <div>
                                {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                            </div>
                            <div class="flex flex-col ml-5">
                                <span class="font-medium">{{ review.user.first_name }}</span>
                                <span class="text-sm text-gray-500">{{ review.created|date:'F Y' }}</span>
                            </div>
                        </div>
                        <p>{{ review.review }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="w-1/3">
        {% if room.host == user %}
            <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_name %}Update Room{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}

    </div>
{% endblock content %} 

templates/rooms/room_list.html
{% extends "base.html" %}
{% load static %}

{% block page_name %}HOME{% endblock page_name %}

{% block content %}
<div class="container mx-auto pb-4 lg:pb-10 md:pb-10">
    <div class="rounded-xl h-25vh mt-16 mb-6 bg-cover bg-center -mx-40 md:mt-24 md:mb-10 md:h-50vh"
        style="background-image:url('{% static "img/main-container.jpg" %}');">
    </div>

    <div class="flex flex-wrap -mb-1 md:-mx-40">
        {% for room in object_list %}
        {% include 'mixins/room_card.html' with room=room %}
        {% endfor %}
    </div>

    <div class="flex items-center justify-center container mt-2 md:mt-0">
        <a {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}" class="text-teal-500 visible"
            {% else %} class="invisible" {% endif %}>
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>

        <span class="mx-3 font-medium text-lg -mt-1">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

        <a {% if page_obj.has_next %} href="?page={{ page_obj.next_page_number }}" class="text-teal-500 visible"
            {% else %} class="invisible" {% endif %}>
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
    </div>
</div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_name %}Search{% endblock page_name %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}
<h2>Search!</h2>

<form method="GET" action="{% url "rooms:search" %}">
    {{ form.as_p }}
    <button>Search</button>
</form>

{% for room in rooms %}
<h3>{{ room.name }}</h3>
{% endfor %}

{% endblock content %}