config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from rooms.views import RoomDetailView, SearchView, RoomEditView

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", RoomEditView.as_view(), name="edit"),
    path("search/", SearchView.as_view(), name="search"),
]

templates/all_rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>All Rooms</title>
</head>
<body>
    <h2>Hello World!</h2>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block page_name %}{% endblock page_name %} | Airbnb</title>
    <link rel="stylesheet" href={% static "css/styles.css" %}>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css">
</head>

<body class="text-gray-700 mt-16 font-light text-sm md:text-base md:mt-24">
    {% include "partials/messages.html" %}
    <header class="container max-w-full inset-0 flex items-center 
    justify-between px-2 h-12 border-b border-gray-400 fixed bg-white md:h-20 md:px-6">
        <div class="flex items-center w-5/6 md:w-1/3">
            <a href='{% url "core:home" %}' class="m-2 md:m-6">
                <img class="w-6 lg:w-8 md:w-8" src="{% static 'img/logo.png' %}" />
            </a>

            {% block search-bar %}
            <form method=" GET" action="{% url "rooms:search" %}" class="w-10/12">
                <input
                    class="search-box border px-5 py-1 pl-8 bg-left-sm bg-sm
                text-sm font-medium text-gray-900 placeholder-gray-600
                w-full rounded-sm shadow-md hover:shadow-lg focus:outline-none md:py-2 md:pl-10 md:bg-left-lg md:bg-lg md:text-nm"
                    name="city" placeholder="Search by City" />
            </form>
            {% endblock search-bar %}
        </div>

        {% include "partials/nav.html" %}
    </header>

    {% block content %}{% endblock content %}

    {% include "partials/footer.html" %}
</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>All Rooms</title>
</head>
<body>
    {% for room in rooms %}
        <h1>{{room}} / ${{room.price}}</h1>
    {% endfor %}
</body>
</html>